INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_MY_PREAMBLE_PILOT my_preamble_pilot)

FIND_PATH(
    MY_PREAMBLE_PILOT_INCLUDE_DIRS
    NAMES my_preamble_pilot/api.h
    HINTS $ENV{MY_PREAMBLE_PILOT_DIR}/include
        ${PC_MY_PREAMBLE_PILOT_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    MY_PREAMBLE_PILOT_LIBRARIES
    NAMES gnuradio-my_preamble_pilot
    HINTS $ENV{MY_PREAMBLE_PILOT_DIR}/lib
        ${PC_MY_PREAMBLE_PILOT_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(MY_PREAMBLE_PILOT DEFAULT_MSG MY_PREAMBLE_PILOT_LIBRARIES MY_PREAMBLE_PILOT_INCLUDE_DIRS)
MARK_AS_ADVANCED(MY_PREAMBLE_PILOT_LIBRARIES MY_PREAMBLE_PILOT_INCLUDE_DIRS)

